<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.web.airline.aos.cvut.cz/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  name="SendEmailWSService" targetNamespace="http://ws.web.airline.aos.cvut.cz/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.web.airline.aos.cvut.cz/" elementFormDefault="unqualified" targetNamespace="http://ws.web.airline.aos.cvut.cz/" version="1.0">

  <xs:element name="sendTicketToEmail" type="tns:sendTicketToEmail"/>

  <xs:element name="sendTicketToEmailResponse" type="tns:sendTicketToEmailResponse"/>

  <xs:complexType name="sendTicketToEmail">
    <xs:sequence>
      <xs:element name="reservationId" type="xs:long"/>
      <xs:element name="emailAddress" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sendTicketToEmailResponse">
    <xs:sequence/>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="sendTicketToEmail">
    <wsdl:part element="tns:sendTicketToEmail" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sendTicketToEmailResponse">
    <wsdl:part element="tns:sendTicketToEmailResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SendEmailWS">
    <wsdl:operation name="sendTicketToEmail">
      <wsdl:input message="tns:sendTicketToEmail" name="sendTicketToEmail">
    </wsdl:input>
      <wsdl:output message="tns:sendTicketToEmailResponse" name="sendTicketToEmailResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SendEmailWSServiceSoapBinding" type="tns:SendEmailWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendTicketToEmail">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sendTicketToEmail">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendTicketToEmailResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SendEmailWSService">
    <wsdl:port binding="tns:SendEmailWSServiceSoapBinding" name="SendEmailWSPort">
      <soap:address location="http://localhost:8080/ws/sendTicketToEmail"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>